<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A2S9SMV" failures="0" tests="4" name="com.oneapp.test_suits.LoginTestCases" time="95.994" errors="1" timestamp="2024-02-20T11:02:32 IST" skipped="0">
  <testcase classname="com.oneapp.test_suits.LoginTestCases" name="TC001_ValidLoginTestCase" time="24.002"/>
  <system-out/>
  <testcase classname="com.oneapp.test_suits.LoginTestCases" name="afterclass" time="0.004">
    <error message="Cannot invoke &quot;com.oneapp.basic.BaseClass.Quit_session()&quot; because &quot;this.baseclass&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.oneapp.basic.BaseClass.Quit_session()" because "this.baseclass" is null
at com.oneapp.basic.BaseClass.afterclass(BaseClass.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- afterclass -->
  <system-out/>
  <testcase classname="com.oneapp.test_suits.LoginTestCases" name="TC001_ValidLoginTestCase" time="39.646"/>
  <system-out/>
  <testcase classname="com.oneapp.test_suits.LoginTestCases" name="TC001_ValidLoginTestCase" time="32.342"/>
  <system-out/>
</testsuite> <!-- com.oneapp.test_suits.LoginTestCases -->
